version: '3'


services:
  webserver:
    networks:
      - my_custom_network

  scheduler:
    networks:
      - my_custom_network

  triggerer:
    networks:
      - my_custom_network

  postgres:
    networks:
      - my_custom_network


  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: mssql22
    environment:
      - SA_PASSWORD=${mssql_password}
      - ACCEPT_EULA=Y
    env_file:
      - .env
    ports:
      - "1433:1433"
    networks:
      - my_custom_network
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-scripts:/var/opt/mssql/scripts
      #- backup_path:/var/opt/mssql/backup
    command: > 
        /bin/bash -c "
        echo 'debug: Log001' &&
        chmod +x /var/opt/mssql/scripts/run_mssql.sh && 
        /var/opt/mssql/scripts/run_mssql.sh &&
        echo 'debug: Log002' &&
        chmod +x /var/opt/mssql/scripts/restore_db.sh && 
        /var/opt/mssql/scripts/restore_db.sh &&
        echo 'debug: Log003'
        "

volumes:
  sql_data:
  
networks:
  my_custom_network:
    name: my_custom_network
    driver: bridge